[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
dns-server = https://dns.yandex.ru/dns-query,tls://77.88.8.8,[2a02:6b8::feed:0ff],[2a02:6b8:0:1::feed:0ff]
# dns-server = tls://9.9.9.9,tls://208.67.222.222
fallback-dns-server = 77.88.8.8,9.9.9.10,208.67.222.222
ipv6 = true
prefer-ipv6 = false
dns-direct-system = false
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = true
dns-direct-fallback-proxy = false
hijack-dns = :53
udp-policy-not-supported-behaviour = REJECT
always-real-ip = time.*.com,ntp.*.com,*.cloudflareclient.com,localhost.sec.qq.com,localhost.ptlogin2.qq.com,localhost.work.weixin.qq.com
update-url = https://raw.githubusercontent.com/SNETLV/SR/refs/heads/main/IN_RU/RU%20Norm%20D.conf
# country: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-Country.mmdb
# asn: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-ASN.mmdb.mmdb


[Rule]
DOMAIN-KEYWORD,google,PROXY
RULE-SET,https://raw.githubusercontent.com/SNETLV/SR/refs/heads/main/IN_RU/messengers.list,PROXY
RULE-SET,https://raw.githubusercontent.com/SNETLV/SR/refs/heads/main/IN_RU/blocked.list,PROXY
RULE-SET,https://raw.githubusercontent.com/SNETLV/SR/refs/heads/main/IN_RU/departed.list,PROXY
GEOIP,US,PROXY
GEOIP,EU,PROXY
# GEOIP,FACEBOOK,PROXY
# GEOIP,CLOUDFLARE,PROXY
# GEOIP,CLOUDFRONT,PROXY
# GEOIP,FASTLY,PROXY
# GEOIP,GOOGLE,PROXY
# GEOIP,NETFLIX,PROXY
# GEOIP,TELEGRAM,PROXY
# GEOIP,TWITTER,PROXY
# Final
FINAL,DIRECT

[Host]
test-cdn-kkk.com = server:tls://208.67.222.222
com-net.cloud = server:tls://9.9.9.12
*.us = server:tls://208.67.222.222
e0f.cx = server:tls://208.67.222.222
*.e0f.cx = server:tls://208.67.222.222
*.e0f.network = server:tls://208.67.222.222
*.cloudflare.com = server:tls://9.9.9.12
localhost = 127.0.0.1

[URL Rewrite]
^https?://(www.)?g.ru https://www.google.com 302
^https?://(www.)?google.ru https://www.google.com 302
