[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
#dns-server = https://doh.opendns.com/dns-query,https://dns.quad9.net/dns-query
dns-server = tls://9.9.9.9,tls://208.67.222.222
fallback-dns-server = 9.9.9.12,208.67.222.222,146.112.41.2
#fallback-dns-server = tls://9.9.9.12,tls://208.67.222.222
ipv6 = true
prefer-ipv6 = false
dns-direct-system = false
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = true
dns-direct-fallback-proxy = false
hijack-dns = :53
udp-policy-not-supported-behaviour = REJECT
always-real-ip = time.*.com,ntp.*.com,*.cloudflareclient.com,localhost.sec.qq.com,localhost.ptlogin2.qq.com,localhost.work.weixin.qq.com
update-url = https://raw.githubusercontent.com/SNETLV/SR/refs/heads/main/IN_RU/RU%20Norm%20P.conf

[Proxy Group]
MES = select,Germany

[Rule]
#Custom Google rewrite
DOMAIN-KEYWORD,google,PROXY
#Rules with domains ru, su, by, kz and similar
RULE-SET,https://raw.githubusercontent.com/SNETLV/SR/refs/heads/main/IN_RU/CIS_domains_ext_UA.list,DIRECT
#Yandex, Mail, Selectel, Tilda and other forced domains
RULE-SET,https://raw.githubusercontent.com/SNETLV/SR/refs/heads/main/IN_RU/providers.list,DIRECT
#TG WA
RULE-SET,https://raw.githubusercontent.com/SNETLV/SR/refs/heads/main/IN_RU/messengers.list,MES
#Force Blocked
RULE-SET,https://raw.githubusercontent.com/SNETLV/SR/refs/heads/main/IN_RU/blocked.list,PROXY
#Apple Force
RULE-SET,https://raw.githubusercontent.com/SNETLV/SR/refs/heads/main/IN_RU/apple_old.list,PROXY
# Final
FINAL,PROXY

[Host]
*.ru = server:77.88.8.8
*.yandex = server:77.88.8.8
dthinkagency.com = server:77.88.8.8
*.dthinkagency.com = server:77.88.8.8
*.su = server:77.88.8.8
*.roistat.com = server:77.88.8.8
*.yastat.net = server:77.88.8.8
*.yastatic.net = server:77.88.8.8
yastat.net = server:77.88.8.8
yastatic.net = server:77.88.8.8
*.yandex.net = server:77.88.8.8
*.yantp.net = server:77.88.8.8
*.timeweb.cloud = server:77.88.8.8
timeweb.cloud = server:77.88.8.8
*.timeweb.com = server:77.88.8.8
*.xn--p1ai = server:77.88.8.8
*.by = server:77.88.8.8
*.xn--90ais = server:77.88.8.8
*.kz = server:77.88.8.8
*.xn--80ao21a = server:77.88.8.8
*.am = server:77.88.8.8
*.az = server:77.88.8.8
*.xn--54b7fta0cc = server:77.88.8.8
*.ge = server:77.88.8.8
*.xn--node = server:77.88.8.8
*.kg = server:77.88.8.8
*.md = server:77.88.8.8
*.tj = server:77.88.8.8
*.tm = server:77.88.8.8
*.uz = server:77.88.8.8
*.xn--80asehdb = server:77.88.8.8
*.xn--80adxhks = server:77.88.8.8
*.xn--80aswg = server:77.88.8.8
*.xn--c1avg = server:77.88.8.8
*.xn--d1acj3b = server:77.88.8.8
*.xn--p1acf = server:77.88.8.8
*.xn--p1ai = server:77.88.8.8
*.tilda.cc = server:77.88.8.8
*.tilda.ws = server:77.88.8.8
*.tildaapi.com = server:77.88.8.8
*.tildaapi.net = server:77.88.8.8
*.tildacdn.com = server:77.88.8.8
*.tildacdn.net = server:77.88.8.8
*.netmonet.co = server:77.88.8.8
*.ngenix.net = server:77.88.8.8
*.ozon.com = server:77.88.8.8
*.ozon.dev = server:77.88.8.8
*.ozon.express = server:77.88.8.8
*.ozon.tech = server:77.88.8.8
*.ozon.travel = server:77.88.8.8
*.ozoncamp.pro = server:77.88.8.8
*.ozonglobalevents.com = server:77.88.8.8
*.ozonru.com = server:77.88.8.8
*.ozonru.me = server:77.88.8.8
*.ozonusercontent.com = server:77.88.8.8
*.paywb.com = server:77.88.8.8
vk.com = server:77.88.8.8
*.vk.com = server:77.88.8.8
beget.com = server:77.88.8.8
*.beget.com = server:77.88.8.8
localhost = 127.0.0.1

[URL Rewrite]
^https?://(www.)?g.ru https://www.google.com 302
^https?://(www.)?google.ru https://www.google.com 302
